#-------------------------------------------------------------------------------------------------------------------------------
#-------------------------------------------------------------------------------------------------------------------------------
#-------------------------------------------  PlayBooK To Configure Plugin --------------------------------------------------
#-------------------------------------------------------------------------------------------------------------------------------
#------------------                    1. It will setup the env for the NodeJS API     ------------------
#-------------------------------------------------------------------------------------------------------------------------------
#--------------      2. It will download the code from the gihub      -------------
#------------------------------------------------------------------------------------------------
#--------------- 3. Download the Required Modules for that modules by the help of package-lock.json ----------------
#--------------------------------------------------------------------------------------
#------------ 4. Server Started On An Specific Port ------------------------------
#-------------------------------------------------------------------------------------------------------------------------------

- hosts :
        - tag_Name_Service

  tasks :
        - name: "Setup the Enviornment"
          package:
                name : "{{ item }}"
                state : present

          with_items:
                - nodejs
                - git
                - curl

        - name : "Download Plugin from github"
          shell : git clone -b plugin https://github.com/Shashwatsingh22/LogManager

        - name : "Lets Install the Required Modules"
          shell : |
                cd /home/ubuntu/LogManager
                npm install

        - name : ""